describe( 'lazyMount', () => {
	let observed, intersectCb, lazyMount, loadAgGrid;

	beforeEach( async () => {
		observed = [];
		intersectCb = null;
		global.agGrid = { createGrid: vi.fn(), themeQuartz: { withParams: () => ( {} ) } };
		global.mw = { config: { get: () => '/w/extensions' }, log: { error: () => {} } };
		// Pretend the bundle is already present so loadAgGrid() resolves without injecting.
		window.agGrid = global.agGrid;
		global.IntersectionObserver = class {
			constructor( cb ) {
				intersectCb = cb;
			}

			observe( el ) {
				observed.push( el );
			}

			unobserve() {}

			disconnect() {}
		};
		// Reset modules so the singleton observer is recreated per test, ensuring
		// the IntersectionObserver constructor (which captures intersectCb) runs fresh.
		vi.resetModules();
		// Concat, not a template literal, so Vite can statically analyse this import.
		// eslint-disable-next-line prefer-template
		( { lazyMount, loadAgGrid } = await import( '../../../modules/ext.aggrid/lazyMount.js?t=' + Date.now() ) );
	} );

	afterEach( () => {
		delete global.agGrid;
		delete global.mw;
		delete global.IntersectionObserver;
		delete window.agGrid;
	} );

	function makeRoot( n ) {
		const root = document.createElement( 'div' );
		for ( let i = 0; i < n; i++ ) {
			const el = document.createElement( 'div' );
			el.className = 'ext-aggrid';
			el.setAttribute( 'data-mw-aggrid-options', '{"columnDefs":[],"rowData":[]}' );
			root.appendChild( el );
		}
		return root;
	}

	it( 'observes each not-yet-mounted placeholder', () => {
		lazyMount( makeRoot( 2 ) );
		expect( observed.length ).toBe( 2 );
	} );

	it( 'loads and mounts a placeholder when it intersects', async () => {
		lazyMount( makeRoot( 1 ) );
		const unobserve = vi.fn();
		intersectCb(
			[ { isIntersecting: true, target: observed[ 0 ] } ],
			{ unobserve }
		);
		await new Promise( ( r ) => {
			setTimeout( r, 0 );
		} );
		expect( unobserve ).toHaveBeenCalledWith( observed[ 0 ] );
		expect( global.agGrid.createGrid ).toHaveBeenCalledTimes( 1 );
	} );

	it( 'does nothing for a non-intersecting entry', () => {
		lazyMount( makeRoot( 1 ) );
		intersectCb( [ { isIntersecting: false, target: observed[ 0 ] } ], { unobserve() {} } );
		expect( global.agGrid.createGrid ).not.toHaveBeenCalled();
	} );

	it( 'falls back to eager mount when IntersectionObserver is unavailable', async () => {
		delete global.IntersectionObserver;
		lazyMount( makeRoot( 2 ) );
		await new Promise( ( r ) => {
			setTimeout( r, 0 );
		} );
		expect( global.agGrid.createGrid ).toHaveBeenCalledTimes( 2 );
	} );

	it( 'resets the memo after a failed load so a second call retries with a new script', async () => {
		// Remove the pre-loaded agGrid so loadAgGrid() actually injects a <script>.
		delete window.agGrid;
		delete global.agGrid;

		const appendSpy = vi.spyOn( document.head, 'appendChild' );

		// First call — promise pending, <script> injected.
		const firstPromise = loadAgGrid();
		const firstScript = appendSpy.mock.calls[ 0 ][ 0 ];

		// Simulate network error — onerror resets the memo.
		firstScript.onerror();

		// The first promise must reject.
		await expect( firstPromise ).rejects.toThrow( 'failed to load AG Grid bundle' );

		// Second call — memo was reset, so a brand-new <script> should be injected.
		loadAgGrid();
		expect( appendSpy ).toHaveBeenCalledTimes( 2 );

		appendSpy.mockRestore();
	} );

	it( 'still resolves when the loaded script defines no agGrid global', async () => {
		delete window.agGrid;
		delete global.agGrid;
		const appendSpy = vi.spyOn( document.head, 'appendChild' );

		const promise = loadAgGrid();
		// A <script> can fire onload having defined no global at all (a captive
		// portal or error page served as JS); onload must still settle the memo.
		appendSpy.mock.calls[ 0 ][ 0 ].onload();

		await expect( promise ).resolves.toBeUndefined();
		appendSpy.mockRestore();
	} );

	it( 'injects the bundle at the server-supplied src', async () => {
		delete window.agGrid;
		delete global.agGrid;
		const appendSpy = vi.spyOn( document.head, 'appendChild' );

		loadAgGrid();

		// On a real wiki ResourceLoader replaces bundle.json with the cache-busted
		// URL Bundle.php builds; here it resolves to the committed placeholder.
		// eslint-disable-next-line prefer-template
		const { src } = await import( '../../../modules/ext.aggrid/bundle.json?t=' + Date.now() );
		// getAttribute, not .src — jsdom absolutises the latter against the page.
		expect( appendSpy.mock.calls[ 0 ][ 0 ].getAttribute( 'src' ) ).toBe( src );

		appendSpy.mockRestore();
	} );
} );

describe( 'bundle.json wiring', () => {
	// lazyMount.js resolves the committed placeholder when ResourceLoader is not
	// involved, so a broken packageFiles entry would not fail any other test — it
	// would just quietly ship the placeholder as the bundle URL forever, which is
	// the exact drift this whole mechanism exists to prevent.
	it( 'is generated by Bundle, not served from disk', async () => {
		const { readFileSync } = await import( 'node:fs' );
		const { resolve } = await import( 'node:path' );
		// Vitest runs from the extension root (where vitest.config.js lives).
		const extensionJson = JSON.parse(
			readFileSync( resolve( process.cwd(), 'extension.json' ), 'utf8' )
		);

		// ResourceLoader collates packageFiles into a map keyed by name, so a later
		// entry silently replaces an earlier one of the same name. bundle.json is a
		// real file sitting beside the others, so adding it to the plain-string
		// list — the natural move when adding a file under modules/ — would quietly
		// swap the callback for the committed placeholder. Assert there is exactly
		// one, not merely that a good one exists somewhere.
		const entries = extensionJson.ResourceModules[ 'ext.aggrid' ].packageFiles
			.filter( ( file ) => (
				typeof file === 'string' ? file : file.name
			) === 'ext.aggrid/bundle.json' );

		expect( entries ).toHaveLength( 1 );
		expect( entries[ 0 ].callback ).toContain( 'Bundle::makePackageFile' );
		expect( entries[ 0 ].versionCallback ).toContain( 'Bundle::getVersionFilePath' );
	} );
} );
