-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/AGGrid/sql/aggrid_source.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE aggrid_source (
  ags_page_id INT NOT NULL,
  ags_grid_index INT NOT NULL,
  ags_source TEXT NOT NULL,
  ags_spec TEXT NOT NULL,
  ags_hash TEXT NOT NULL,
  PRIMARY KEY(ags_page_id, ags_grid_index)
);
