-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE aggrid_data (
  agd_page_id INT NOT NULL,
  agd_grid_index INT NOT NULL,
  agd_rows TEXT NOT NULL,
  agd_row_count INT NOT NULL,
  agd_hash TEXT NOT NULL,
  PRIMARY KEY(agd_page_id, agd_grid_index)
);
