-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/AGGrid/sql/aggrid_source.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aggrid_source (
  ags_page_id INTEGER UNSIGNED NOT NULL,
  ags_grid_index INTEGER UNSIGNED NOT NULL,
  ags_source BLOB NOT NULL,
  ags_spec BLOB NOT NULL,
  ags_hash BLOB NOT NULL,
  PRIMARY KEY(ags_page_id, ags_grid_index)
);
