-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aggrid_data (
  agd_page_id INTEGER UNSIGNED NOT NULL,
  agd_grid_index INTEGER UNSIGNED NOT NULL,
  agd_rows BLOB NOT NULL,
  agd_row_count INTEGER UNSIGNED NOT NULL,
  agd_hash BLOB NOT NULL,
  PRIMARY KEY(agd_page_id, agd_grid_index)
);
