-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/AGGrid/sql/aggrid_source.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aggrid_source (
  ags_page_id INT UNSIGNED NOT NULL,
  ags_grid_index INT UNSIGNED NOT NULL,
  ags_source VARBINARY(32) NOT NULL,
  ags_spec MEDIUMBLOB NOT NULL,
  ags_hash BINARY(40) NOT NULL,
  PRIMARY KEY(ags_page_id, ags_grid_index)
) /*$wgDBTableOptions*/;
