-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/AGGrid/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aggrid_data (
  agd_page_id INT UNSIGNED NOT NULL,
  agd_grid_index INT UNSIGNED NOT NULL,
  agd_rows MEDIUMBLOB NOT NULL,
  agd_row_count INT UNSIGNED NOT NULL,
  agd_hash BINARY(40) NOT NULL,
  PRIMARY KEY(agd_page_id, agd_grid_index)
) /*$wgDBTableOptions*/;
